// stdafx.h : 可在此標頭檔中包含標準的系統 Include 檔，
// 或是經常使用卻很少變更的
// 專案專用 Include 檔案
//

#pragma once

/**
*	@brief Header files for the C++ utility library
*/
#include <cassert>
#include <utility>
#include <stdlib.h>

/**
*	@brief Header files for the STL library
*/
#include <iostream>
#include <fstream>
#include <vector>
#include <map>
#include <set>
#include <string>
#include <cmath>
#include <list>
#include <limits>
#include <algorithm>
#include <functional>
#include <numeric>
#include <random>
#include <sstream>
// #include <strstream> UNLIN
#include <exception>
#include <unordered_map>
#include <unordered_set>
using namespace std;
/**
*	@brief Header files for QR code generator Library
*/
#include "qrencode/Include/qrencode.h"
#include "qrencode/Include/qrspec.h"

#ifdef NDEBUG
#pragma comment( lib, "qrencode/Lib/QREncode.lib" )
#pragma message( "Link with QREncode.lib." )
#else
#pragma comment( lib, "qrencode/Lib/QREncoded.lib" )
#pragma message( "Link with QREncoded.lib." )
#endif

/**
*	@brief Header files for the boost library
*/
#include <boost/graph/adjacency_list.hpp>

/**
*	@brief Header files for OpenCV library 2.4.1
*/
/// Disable warnings generated by OpenCV
/// 'cv::XXXX' : function compiled as native
#pragma warning( disable:4793 )
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define LIBFILE(x) x ".lib"
#define LIBdFILE(x) x "d.lib"
#include <opencv2/opencv.hpp>
#define OPENCV_VER 246
#define OPENCV_CORE "opencv_core" TOSTRING(OPENCV_VER)
#define OPENCV_IMGPROC "opencv_imgproc" TOSTRING(OPENCV_VER)
#define OPENCV_HIGHGUI "opencv_highgui" TOSTRING(OPENCV_VER)
#define OPENCV_VIDEO "opencv_video" TOSTRING(OPENCV_VER)
#define OPENCV_FEATURES2D "opencv_features2d" TOSTRING(OPENCV_VER)
#define OPENCV_OBJDETECT "opencv_objdetect" TOSTRING(OPENCV_VER)
#define OPENCV_ML "opencv_ml" TOSTRING(OPENCV_VER)
#define OPENCV_CALIB3D "opencv_calib3d" TOSTRING(OPENCV_VER)
#define OPENCV_CONTRIB "opencv_contrib" TOSTRING(OPENCV_VER)
#define OPENCV_LEGACY "opencv_legacy" TOSTRING(OPENCV_VER)
#define OPENCV_FLANN "opencv_flann" TOSTRING(OPENCV_VER)
#ifdef NDEBUG
#pragma comment( lib, LIBFILE(OPENCV_CORE))
#pragma message( "Link with " LIBFILE(OPENCV_CORE) )
#pragma comment( lib, LIBFILE(OPENCV_IMGPROC) )
#pragma message( "Link with " LIBFILE(OPENCV_IMGPROC) )
#pragma comment( lib, LIBFILE(OPENCV_HIGHGUI) )
#pragma message( "Link with " LIBFILE(OPENCV_HIGHGUI) )
#pragma comment( lib, LIBFILE(OPENCV_VIDEO) )
#pragma message( "Link with " LIBFILE(OPENCV_VIDEO) )
#pragma comment( lib, LIBFILE(OPENCV_FEATURES2D) )
#pragma message( "Link with " LIBFILE(OPENCV_FEATURES2D) )
#pragma comment( lib, LIBFILE(OPENCV_OBJDETECT) )
#pragma message( "Link with " LIBFILE(OPENCV_OBJDETECT) )
//#pragma comment( lib, LIBFILE(OPENCV_ML) )
//#pragma message( "Link with " LIBFILE(OPENCV_ML) )
//#pragma comment( lib, LIBFILE(OPENCV_CALIB3D) )
//#pragma message( "Link with " LIBFILE(OPENCV_CALIB3D) )
//#pragma comment( lib, LIBFILE(OPENCV_CONTRIB) )
//#pragma message( "Link with " LIBFILE(OPENCV_CONTRIB) )
//#pragma comment( lib, LIBFILE(OPENCV_LEGACY) )
//#pragma message( "Link with " LIBFILE(OPENCV_LEGACY) )
//#pragma comment( lib, LIBFILE(OPENCV_FLANN) )
//#pragma message( "Link with " LIBFILE(OPENCV_FLANN) )
#else
#pragma comment( lib, LIBdFILE(OPENCV_CORE))
#pragma message( "Link with " LIBdFILE(OPENCV_CORE) )
#pragma comment( lib, LIBdFILE(OPENCV_IMGPROC) )
#pragma message( "Link with " LIBdFILE(OPENCV_IMGPROC) )
#pragma comment( lib, LIBdFILE(OPENCV_HIGHGUI) )
#pragma message( "Link with " LIBdFILE(OPENCV_HIGHGUI) )
#pragma comment( lib, LIBdFILE(OPENCV_VIDEO) )
#pragma message( "Link with " LIBdFILE(OPENCV_VIDEO) )
#pragma comment( lib, LIBdFILE(OPENCV_FEATURES2D) )
#pragma message( "Link with " LIBdFILE(OPENCV_FEATURES2D) )
#pragma comment( lib, LIBdFILE(OPENCV_OBJDETECT) )
#pragma message( "Link with " LIBdFILE(OPENCV_OBJDETECT) )
//#pragma comment( lib, LIBdFILE(OPENCV_ML) )
//#pragma message( "Link with " LIBdFILE(OPENCV_ML) )
//#pragma comment( lib, LIBdFILE(OPENCV_CALIB3D) )
//#pragma message( "Link with " LIBdFILE(OPENCV_CALIB3D) )
//#pragma comment( lib, LIBdFILE(OPENCV_CONTRIB) )
//#pragma message( "Link with " LIBdFILE(OPENCV_CONTRIB) )
//#pragma comment( lib, LIBdFILE(OPENCV_LEGACY) )
//#pragma message( "Link with " LIBdFILE(OPENCV_LEGACY) )
//#pragma comment( lib, LIBdFILE(OPENCV_FLANN) )
//#pragma message( "Link with " LIBdFILE(OPENCV_FLANN) )
#endif

#include "GCO/energy.h"
#include "GCO/GCoptimization.h"
#pragma comment( lib, "GCoptimization.lib" )
#pragma message( "Link with GCoptimization.lib" )
#include "GCO/LinkedBlockList.h"
#pragma comment( lib, "LinkedBlockList.lib" )
#pragma message( "Link with LinkedBlockList.lib" )


// TODO: 在此參考您的程式所需要的其他標頭
